
// This file has been generated by the GUI designer. Do not modify.

public partial class MainWindow
{
	private global::Gtk.VBox vbox20;
	
	private global::Gtk.HBox hbox9;
	
	private global::Gtk.Label label;
	
	private global::Gtk.Entry screen;
	
	private global::Gtk.Button buttonClear;
	
	private global::Gtk.Table table2;
	
	private global::Gtk.Button button1;
	
	private global::Gtk.Button button2;
	
	private global::Gtk.Button button4;
	
	private global::Gtk.Button button5;
	
	private global::Gtk.Button button7;
	
	private global::Gtk.Button button8;
	
	private global::Gtk.HBox hbox6;
	
	private global::Gtk.Button button3;
	
	private global::Gtk.Button buttonAdd;
	
	private global::Gtk.Button buttonSubstract;
	
	private global::Gtk.HBox hbox7;
	
	private global::Gtk.Button button6;
	
	private global::Gtk.Button buttonMultiplicate;
	
	private global::Gtk.Button buttonDivide;
	
	private global::Gtk.HBox hbox8;
	
	private global::Gtk.Button button9;
	
	private global::Gtk.Button buttonZero;
	
	private global::Gtk.Button buttonResult;

	protected virtual void Build ()
	{
		global::Stetic.Gui.Initialize (this);
		// Widget MainWindow
		this.Name = "MainWindow";
		this.Title = global::Mono.Unix.Catalog.GetString ("MainWindow");
		this.WindowPosition = ((global::Gtk.WindowPosition)(4));
		// Container child MainWindow.Gtk.Container+ContainerChild
		this.vbox20 = new global::Gtk.VBox ();
		this.vbox20.Name = "vbox20";
		this.vbox20.Spacing = 6;
		// Container child vbox20.Gtk.Box+BoxChild
		this.hbox9 = new global::Gtk.HBox ();
		this.hbox9.Name = "hbox9";
		this.hbox9.Spacing = 6;
		// Container child hbox9.Gtk.Box+BoxChild
		this.label = new global::Gtk.Label ();
		this.label.Name = "label";
		this.label.LabelProp = global::Mono.Unix.Catalog.GetString (" Result: ");
		this.hbox9.Add (this.label);
		global::Gtk.Box.BoxChild w1 = ((global::Gtk.Box.BoxChild)(this.hbox9 [this.label]));
		w1.Position = 0;
		w1.Expand = false;
		w1.Fill = false;
		// Container child hbox9.Gtk.Box+BoxChild
		this.screen = new global::Gtk.Entry ();
		this.screen.CanFocus = true;
		this.screen.Name = "screen";
		this.screen.IsEditable = false;
		this.screen.InvisibleChar = '●';
		this.hbox9.Add (this.screen);
		global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.hbox9 [this.screen]));
		w2.Position = 1;
		// Container child hbox9.Gtk.Box+BoxChild
		this.buttonClear = new global::Gtk.Button ();
		this.buttonClear.WidthRequest = 50;
		this.buttonClear.HeightRequest = 50;
		this.buttonClear.CanFocus = true;
		this.buttonClear.Name = "buttonClear";
		this.buttonClear.UseUnderline = true;
		this.buttonClear.Label = global::Mono.Unix.Catalog.GetString ("clear ");
		this.hbox9.Add (this.buttonClear);
		global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.hbox9 [this.buttonClear]));
		w3.Position = 2;
		w3.Fill = false;
		this.vbox20.Add (this.hbox9);
		global::Gtk.Box.BoxChild w4 = ((global::Gtk.Box.BoxChild)(this.vbox20 [this.hbox9]));
		w4.Position = 0;
		w4.Expand = false;
		w4.Fill = false;
		// Container child vbox20.Gtk.Box+BoxChild
		this.table2 = new global::Gtk.Table (((uint)(3)), ((uint)(3)), false);
		this.table2.Name = "table2";
		this.table2.RowSpacing = ((uint)(6));
		this.table2.ColumnSpacing = ((uint)(6));
		// Container child table2.Gtk.Table+TableChild
		this.button1 = new global::Gtk.Button ();
		this.button1.WidthRequest = 50;
		this.button1.HeightRequest = 50;
		this.button1.CanFocus = true;
		this.button1.Name = "button1";
		this.button1.UseUnderline = true;
		this.button1.Label = global::Mono.Unix.Catalog.GetString ("1");
		this.table2.Add (this.button1);
		global::Gtk.Table.TableChild w5 = ((global::Gtk.Table.TableChild)(this.table2 [this.button1]));
		w5.XOptions = ((global::Gtk.AttachOptions)(4));
		w5.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table2.Gtk.Table+TableChild
		this.button2 = new global::Gtk.Button ();
		this.button2.WidthRequest = 50;
		this.button2.HeightRequest = 50;
		this.button2.CanFocus = true;
		this.button2.Name = "button2";
		this.button2.UseUnderline = true;
		this.button2.Label = global::Mono.Unix.Catalog.GetString ("2");
		this.table2.Add (this.button2);
		global::Gtk.Table.TableChild w6 = ((global::Gtk.Table.TableChild)(this.table2 [this.button2]));
		w6.LeftAttach = ((uint)(1));
		w6.RightAttach = ((uint)(2));
		w6.XOptions = ((global::Gtk.AttachOptions)(4));
		w6.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table2.Gtk.Table+TableChild
		this.button4 = new global::Gtk.Button ();
		this.button4.WidthRequest = 50;
		this.button4.HeightRequest = 50;
		this.button4.CanFocus = true;
		this.button4.Name = "button4";
		this.button4.UseUnderline = true;
		this.button4.Label = global::Mono.Unix.Catalog.GetString ("4");
		this.table2.Add (this.button4);
		global::Gtk.Table.TableChild w7 = ((global::Gtk.Table.TableChild)(this.table2 [this.button4]));
		w7.TopAttach = ((uint)(1));
		w7.BottomAttach = ((uint)(2));
		w7.XOptions = ((global::Gtk.AttachOptions)(4));
		w7.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table2.Gtk.Table+TableChild
		this.button5 = new global::Gtk.Button ();
		this.button5.WidthRequest = 50;
		this.button5.HeightRequest = 50;
		this.button5.CanFocus = true;
		this.button5.Name = "button5";
		this.button5.UseUnderline = true;
		this.button5.Label = global::Mono.Unix.Catalog.GetString ("5");
		this.table2.Add (this.button5);
		global::Gtk.Table.TableChild w8 = ((global::Gtk.Table.TableChild)(this.table2 [this.button5]));
		w8.TopAttach = ((uint)(1));
		w8.BottomAttach = ((uint)(2));
		w8.LeftAttach = ((uint)(1));
		w8.RightAttach = ((uint)(2));
		w8.XOptions = ((global::Gtk.AttachOptions)(4));
		w8.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table2.Gtk.Table+TableChild
		this.button7 = new global::Gtk.Button ();
		this.button7.WidthRequest = 50;
		this.button7.HeightRequest = 50;
		this.button7.CanFocus = true;
		this.button7.Name = "button7";
		this.button7.UseUnderline = true;
		this.button7.Label = global::Mono.Unix.Catalog.GetString ("7");
		this.table2.Add (this.button7);
		global::Gtk.Table.TableChild w9 = ((global::Gtk.Table.TableChild)(this.table2 [this.button7]));
		w9.TopAttach = ((uint)(2));
		w9.BottomAttach = ((uint)(3));
		w9.XOptions = ((global::Gtk.AttachOptions)(4));
		w9.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table2.Gtk.Table+TableChild
		this.button8 = new global::Gtk.Button ();
		this.button8.WidthRequest = 50;
		this.button8.HeightRequest = 50;
		this.button8.CanFocus = true;
		this.button8.Name = "button8";
		this.button8.UseUnderline = true;
		this.button8.Label = global::Mono.Unix.Catalog.GetString ("8");
		this.table2.Add (this.button8);
		global::Gtk.Table.TableChild w10 = ((global::Gtk.Table.TableChild)(this.table2 [this.button8]));
		w10.TopAttach = ((uint)(2));
		w10.BottomAttach = ((uint)(3));
		w10.LeftAttach = ((uint)(1));
		w10.RightAttach = ((uint)(2));
		w10.XOptions = ((global::Gtk.AttachOptions)(4));
		w10.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table2.Gtk.Table+TableChild
		this.hbox6 = new global::Gtk.HBox ();
		this.hbox6.Name = "hbox6";
		this.hbox6.Spacing = 6;
		// Container child hbox6.Gtk.Box+BoxChild
		this.button3 = new global::Gtk.Button ();
		this.button3.WidthRequest = 50;
		this.button3.HeightRequest = 50;
		this.button3.CanFocus = true;
		this.button3.Name = "button3";
		this.button3.UseUnderline = true;
		this.button3.Label = global::Mono.Unix.Catalog.GetString ("3");
		this.hbox6.Add (this.button3);
		global::Gtk.Box.BoxChild w11 = ((global::Gtk.Box.BoxChild)(this.hbox6 [this.button3]));
		w11.Position = 0;
		w11.Expand = false;
		w11.Fill = false;
		// Container child hbox6.Gtk.Box+BoxChild
		this.buttonAdd = new global::Gtk.Button ();
		this.buttonAdd.WidthRequest = 50;
		this.buttonAdd.HeightRequest = 50;
		this.buttonAdd.CanFocus = true;
		this.buttonAdd.Name = "buttonAdd";
		this.buttonAdd.UseUnderline = true;
		this.buttonAdd.Label = global::Mono.Unix.Catalog.GetString ("+");
		this.hbox6.Add (this.buttonAdd);
		global::Gtk.Box.BoxChild w12 = ((global::Gtk.Box.BoxChild)(this.hbox6 [this.buttonAdd]));
		w12.Position = 1;
		w12.Expand = false;
		w12.Fill = false;
		// Container child hbox6.Gtk.Box+BoxChild
		this.buttonSubstract = new global::Gtk.Button ();
		this.buttonSubstract.WidthRequest = 50;
		this.buttonSubstract.HeightRequest = 50;
		this.buttonSubstract.CanFocus = true;
		this.buttonSubstract.Name = "buttonSubstract";
		this.buttonSubstract.UseUnderline = true;
		this.buttonSubstract.Label = global::Mono.Unix.Catalog.GetString ("-");
		this.hbox6.Add (this.buttonSubstract);
		global::Gtk.Box.BoxChild w13 = ((global::Gtk.Box.BoxChild)(this.hbox6 [this.buttonSubstract]));
		w13.Position = 2;
		w13.Expand = false;
		w13.Fill = false;
		this.table2.Add (this.hbox6);
		global::Gtk.Table.TableChild w14 = ((global::Gtk.Table.TableChild)(this.table2 [this.hbox6]));
		w14.LeftAttach = ((uint)(2));
		w14.RightAttach = ((uint)(3));
		w14.XOptions = ((global::Gtk.AttachOptions)(4));
		w14.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table2.Gtk.Table+TableChild
		this.hbox7 = new global::Gtk.HBox ();
		this.hbox7.Name = "hbox7";
		this.hbox7.Spacing = 6;
		// Container child hbox7.Gtk.Box+BoxChild
		this.button6 = new global::Gtk.Button ();
		this.button6.WidthRequest = 50;
		this.button6.HeightRequest = 50;
		this.button6.CanFocus = true;
		this.button6.Name = "button6";
		this.button6.UseUnderline = true;
		this.button6.Label = global::Mono.Unix.Catalog.GetString ("6");
		this.hbox7.Add (this.button6);
		global::Gtk.Box.BoxChild w15 = ((global::Gtk.Box.BoxChild)(this.hbox7 [this.button6]));
		w15.Position = 0;
		w15.Expand = false;
		w15.Fill = false;
		// Container child hbox7.Gtk.Box+BoxChild
		this.buttonMultiplicate = new global::Gtk.Button ();
		this.buttonMultiplicate.WidthRequest = 50;
		this.buttonMultiplicate.HeightRequest = 50;
		this.buttonMultiplicate.CanFocus = true;
		this.buttonMultiplicate.Name = "buttonMultiplicate";
		this.buttonMultiplicate.UseUnderline = true;
		this.buttonMultiplicate.Label = global::Mono.Unix.Catalog.GetString ("*");
		this.hbox7.Add (this.buttonMultiplicate);
		global::Gtk.Box.BoxChild w16 = ((global::Gtk.Box.BoxChild)(this.hbox7 [this.buttonMultiplicate]));
		w16.Position = 1;
		w16.Expand = false;
		w16.Fill = false;
		// Container child hbox7.Gtk.Box+BoxChild
		this.buttonDivide = new global::Gtk.Button ();
		this.buttonDivide.WidthRequest = 50;
		this.buttonDivide.HeightRequest = 50;
		this.buttonDivide.CanFocus = true;
		this.buttonDivide.Name = "buttonDivide";
		this.buttonDivide.UseUnderline = true;
		this.buttonDivide.Label = global::Mono.Unix.Catalog.GetString ("/");
		this.hbox7.Add (this.buttonDivide);
		global::Gtk.Box.BoxChild w17 = ((global::Gtk.Box.BoxChild)(this.hbox7 [this.buttonDivide]));
		w17.Position = 2;
		w17.Expand = false;
		w17.Fill = false;
		this.table2.Add (this.hbox7);
		global::Gtk.Table.TableChild w18 = ((global::Gtk.Table.TableChild)(this.table2 [this.hbox7]));
		w18.TopAttach = ((uint)(1));
		w18.BottomAttach = ((uint)(2));
		w18.LeftAttach = ((uint)(2));
		w18.RightAttach = ((uint)(3));
		w18.XOptions = ((global::Gtk.AttachOptions)(4));
		w18.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table2.Gtk.Table+TableChild
		this.hbox8 = new global::Gtk.HBox ();
		this.hbox8.Name = "hbox8";
		this.hbox8.Spacing = 6;
		// Container child hbox8.Gtk.Box+BoxChild
		this.button9 = new global::Gtk.Button ();
		this.button9.WidthRequest = 50;
		this.button9.HeightRequest = 50;
		this.button9.CanFocus = true;
		this.button9.Name = "button9";
		this.button9.UseUnderline = true;
		this.button9.Label = global::Mono.Unix.Catalog.GetString ("9");
		this.hbox8.Add (this.button9);
		global::Gtk.Box.BoxChild w19 = ((global::Gtk.Box.BoxChild)(this.hbox8 [this.button9]));
		w19.Position = 0;
		w19.Expand = false;
		w19.Fill = false;
		// Container child hbox8.Gtk.Box+BoxChild
		this.buttonZero = new global::Gtk.Button ();
		this.buttonZero.WidthRequest = 50;
		this.buttonZero.HeightRequest = 50;
		this.buttonZero.CanFocus = true;
		this.buttonZero.Name = "buttonZero";
		this.buttonZero.UseUnderline = true;
		this.buttonZero.Label = global::Mono.Unix.Catalog.GetString ("0");
		this.hbox8.Add (this.buttonZero);
		global::Gtk.Box.BoxChild w20 = ((global::Gtk.Box.BoxChild)(this.hbox8 [this.buttonZero]));
		w20.Position = 1;
		w20.Expand = false;
		w20.Fill = false;
		// Container child hbox8.Gtk.Box+BoxChild
		this.buttonResult = new global::Gtk.Button ();
		this.buttonResult.WidthRequest = 50;
		this.buttonResult.HeightRequest = 50;
		this.buttonResult.CanFocus = true;
		this.buttonResult.Name = "buttonResult";
		this.buttonResult.UseUnderline = true;
		this.buttonResult.Label = global::Mono.Unix.Catalog.GetString ("=");
		this.hbox8.Add (this.buttonResult);
		global::Gtk.Box.BoxChild w21 = ((global::Gtk.Box.BoxChild)(this.hbox8 [this.buttonResult]));
		w21.Position = 2;
		w21.Expand = false;
		w21.Fill = false;
		this.table2.Add (this.hbox8);
		global::Gtk.Table.TableChild w22 = ((global::Gtk.Table.TableChild)(this.table2 [this.hbox8]));
		w22.TopAttach = ((uint)(2));
		w22.BottomAttach = ((uint)(3));
		w22.LeftAttach = ((uint)(2));
		w22.RightAttach = ((uint)(3));
		w22.XOptions = ((global::Gtk.AttachOptions)(4));
		w22.YOptions = ((global::Gtk.AttachOptions)(4));
		this.vbox20.Add (this.table2);
		global::Gtk.Box.BoxChild w23 = ((global::Gtk.Box.BoxChild)(this.vbox20 [this.table2]));
		w23.Position = 1;
		w23.Expand = false;
		w23.Fill = false;
		this.Add (this.vbox20);
		if ((this.Child != null)) {
			this.Child.ShowAll ();
		}
		this.DefaultWidth = 277;
		this.DefaultHeight = 223;
		this.Show ();
		this.DeleteEvent += new global::Gtk.DeleteEventHandler (this.OnDeleteEvent);
		this.buttonClear.Clicked += new global::System.EventHandler (this.OnButtonClearClicked);
		this.button9.Clicked += new global::System.EventHandler (this.OnButtonClicked);
		this.buttonZero.Clicked += new global::System.EventHandler (this.OnButtonClicked);
		this.buttonResult.Clicked += new global::System.EventHandler (this.OnButtonResultClicked);
		this.button6.Clicked += new global::System.EventHandler (this.OnButtonClicked);
		this.buttonMultiplicate.Clicked += new global::System.EventHandler (this.OnButtonOperationClicked);
		this.buttonDivide.Clicked += new global::System.EventHandler (this.OnButtonOperationClicked);
		this.button3.Clicked += new global::System.EventHandler (this.OnButtonClicked);
		this.buttonAdd.Clicked += new global::System.EventHandler (this.OnButtonOperationClicked);
		this.buttonSubstract.Clicked += new global::System.EventHandler (this.OnButtonOperationClicked);
		this.button8.Clicked += new global::System.EventHandler (this.OnButtonClicked);
		this.button7.Clicked += new global::System.EventHandler (this.OnButtonClicked);
		this.button5.Clicked += new global::System.EventHandler (this.OnButtonClicked);
		this.button4.Clicked += new global::System.EventHandler (this.OnButtonClicked);
		this.button2.Clicked += new global::System.EventHandler (this.OnButtonClicked);
		this.button1.Clicked += new global::System.EventHandler (this.OnButtonClicked);
	}
}
