
// This file has been generated by the GUI designer. Do not modify.

public partial class MainWindow
{
	private global::Gtk.HBox hbox4;
	
	private global::Gtk.VBox vbox6;
	
	private global::Gtk.Button button1;
	
	private global::Gtk.Button button4;
	
	private global::Gtk.Button button7;
	
	private global::Gtk.VBox vbox4;
	
	private global::Gtk.Button button2;
	
	private global::Gtk.Button button5;
	
	private global::Gtk.Button button8;
	
	private global::Gtk.VBox vbox7;
	
	private global::Gtk.Label resultScreen;
	
	private global::Gtk.VBox vbox3;
	
	private global::Gtk.Button button3;
	
	private global::Gtk.Button button6;
	
	private global::Gtk.Button button9;

	protected virtual void Build ()
	{
		global::Stetic.Gui.Initialize (this);
		// Widget MainWindow
		this.Name = "MainWindow";
		this.Title = global::Mono.Unix.Catalog.GetString ("MainWindow");
		this.WindowPosition = ((global::Gtk.WindowPosition)(4));
		// Container child MainWindow.Gtk.Container+ContainerChild
		this.hbox4 = new global::Gtk.HBox ();
		this.hbox4.Name = "hbox4";
		this.hbox4.Spacing = 6;
		// Container child hbox4.Gtk.Box+BoxChild
		this.vbox6 = new global::Gtk.VBox ();
		this.vbox6.Name = "vbox6";
		this.vbox6.Spacing = 6;
		// Container child vbox6.Gtk.Box+BoxChild
		this.button1 = new global::Gtk.Button ();
		this.button1.WidthRequest = 100;
		this.button1.HeightRequest = 100;
		this.button1.CanFocus = true;
		this.button1.Name = "button1";
		this.button1.UseUnderline = true;
		this.vbox6.Add (this.button1);
		global::Gtk.Box.BoxChild w1 = ((global::Gtk.Box.BoxChild)(this.vbox6 [this.button1]));
		w1.Position = 0;
		w1.Expand = false;
		w1.Fill = false;
		// Container child vbox6.Gtk.Box+BoxChild
		this.button4 = new global::Gtk.Button ();
		this.button4.WidthRequest = 100;
		this.button4.HeightRequest = 100;
		this.button4.CanFocus = true;
		this.button4.Name = "button4";
		this.button4.UseUnderline = true;
		this.vbox6.Add (this.button4);
		global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.vbox6 [this.button4]));
		w2.Position = 1;
		w2.Expand = false;
		w2.Fill = false;
		// Container child vbox6.Gtk.Box+BoxChild
		this.button7 = new global::Gtk.Button ();
		this.button7.WidthRequest = 100;
		this.button7.HeightRequest = 100;
		this.button7.CanFocus = true;
		this.button7.Name = "button7";
		this.button7.UseUnderline = true;
		this.vbox6.Add (this.button7);
		global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.vbox6 [this.button7]));
		w3.Position = 2;
		w3.Expand = false;
		w3.Fill = false;
		this.hbox4.Add (this.vbox6);
		global::Gtk.Box.BoxChild w4 = ((global::Gtk.Box.BoxChild)(this.hbox4 [this.vbox6]));
		w4.Position = 0;
		w4.Expand = false;
		w4.Fill = false;
		// Container child hbox4.Gtk.Box+BoxChild
		this.vbox4 = new global::Gtk.VBox ();
		this.vbox4.Name = "vbox4";
		this.vbox4.Spacing = 6;
		// Container child vbox4.Gtk.Box+BoxChild
		this.button2 = new global::Gtk.Button ();
		this.button2.WidthRequest = 100;
		this.button2.HeightRequest = 100;
		this.button2.CanFocus = true;
		this.button2.Name = "button2";
		this.button2.UseUnderline = true;
		this.vbox4.Add (this.button2);
		global::Gtk.Box.BoxChild w5 = ((global::Gtk.Box.BoxChild)(this.vbox4 [this.button2]));
		w5.Position = 0;
		w5.Expand = false;
		w5.Fill = false;
		// Container child vbox4.Gtk.Box+BoxChild
		this.button5 = new global::Gtk.Button ();
		this.button5.WidthRequest = 100;
		this.button5.HeightRequest = 100;
		this.button5.CanFocus = true;
		this.button5.Name = "button5";
		this.button5.UseUnderline = true;
		this.vbox4.Add (this.button5);
		global::Gtk.Box.BoxChild w6 = ((global::Gtk.Box.BoxChild)(this.vbox4 [this.button5]));
		w6.Position = 1;
		w6.Expand = false;
		w6.Fill = false;
		// Container child vbox4.Gtk.Box+BoxChild
		this.button8 = new global::Gtk.Button ();
		this.button8.WidthRequest = 100;
		this.button8.HeightRequest = 100;
		this.button8.CanFocus = true;
		this.button8.Name = "button8";
		this.button8.UseUnderline = true;
		this.vbox4.Add (this.button8);
		global::Gtk.Box.BoxChild w7 = ((global::Gtk.Box.BoxChild)(this.vbox4 [this.button8]));
		w7.Position = 2;
		w7.Expand = false;
		w7.Fill = false;
		// Container child vbox4.Gtk.Box+BoxChild
		this.vbox7 = new global::Gtk.VBox ();
		this.vbox7.Name = "vbox7";
		this.vbox7.Spacing = 6;
		// Container child vbox7.Gtk.Box+BoxChild
		this.resultScreen = new global::Gtk.Label ();
		this.resultScreen.Name = "resultScreen";
		this.vbox7.Add (this.resultScreen);
		global::Gtk.Box.BoxChild w8 = ((global::Gtk.Box.BoxChild)(this.vbox7 [this.resultScreen]));
		w8.Position = 0;
		w8.Expand = false;
		w8.Fill = false;
		this.vbox4.Add (this.vbox7);
		global::Gtk.Box.BoxChild w9 = ((global::Gtk.Box.BoxChild)(this.vbox4 [this.vbox7]));
		w9.Position = 3;
		w9.Expand = false;
		w9.Fill = false;
		this.hbox4.Add (this.vbox4);
		global::Gtk.Box.BoxChild w10 = ((global::Gtk.Box.BoxChild)(this.hbox4 [this.vbox4]));
		w10.Position = 1;
		w10.Expand = false;
		w10.Fill = false;
		// Container child hbox4.Gtk.Box+BoxChild
		this.vbox3 = new global::Gtk.VBox ();
		this.vbox3.Name = "vbox3";
		this.vbox3.Spacing = 6;
		// Container child vbox3.Gtk.Box+BoxChild
		this.button3 = new global::Gtk.Button ();
		this.button3.WidthRequest = 100;
		this.button3.HeightRequest = 100;
		this.button3.CanFocus = true;
		this.button3.Name = "button3";
		this.button3.UseUnderline = true;
		this.vbox3.Add (this.button3);
		global::Gtk.Box.BoxChild w11 = ((global::Gtk.Box.BoxChild)(this.vbox3 [this.button3]));
		w11.Position = 0;
		w11.Expand = false;
		w11.Fill = false;
		// Container child vbox3.Gtk.Box+BoxChild
		this.button6 = new global::Gtk.Button ();
		this.button6.WidthRequest = 100;
		this.button6.HeightRequest = 100;
		this.button6.CanFocus = true;
		this.button6.Name = "button6";
		this.button6.UseUnderline = true;
		this.vbox3.Add (this.button6);
		global::Gtk.Box.BoxChild w12 = ((global::Gtk.Box.BoxChild)(this.vbox3 [this.button6]));
		w12.Position = 1;
		w12.Expand = false;
		w12.Fill = false;
		// Container child vbox3.Gtk.Box+BoxChild
		this.button9 = new global::Gtk.Button ();
		this.button9.WidthRequest = 100;
		this.button9.HeightRequest = 100;
		this.button9.CanFocus = true;
		this.button9.UseUnderline = true;
		this.vbox3.Add (this.button9);
		global::Gtk.Box.BoxChild w13 = ((global::Gtk.Box.BoxChild)(this.vbox3 [this.button9]));
		w13.Position = 2;
		w13.Expand = false;
		w13.Fill = false;
		this.hbox4.Add (this.vbox3);
		global::Gtk.Box.BoxChild w14 = ((global::Gtk.Box.BoxChild)(this.hbox4 [this.vbox3]));
		w14.Position = 2;
		w14.Expand = false;
		w14.Fill = false;
		this.Add (this.hbox4);
		if ((this.Child != null)) {
			this.Child.ShowAll ();
		}
		this.DefaultWidth = 314;
		this.DefaultHeight = 341;
		this.Show ();
		this.DeleteEvent += new global::Gtk.DeleteEventHandler (this.OnDeleteEvent);
		this.button1.Clicked += new global::System.EventHandler (this.OnButtonClicked);
		this.button4.Clicked += new global::System.EventHandler (this.OnButtonClicked);
		this.button7.Clicked += new global::System.EventHandler (this.OnButtonClicked);
		this.button2.Clicked += new global::System.EventHandler (this.OnButtonClicked);
		this.button5.Clicked += new global::System.EventHandler (this.OnButtonClicked);
		this.button8.Clicked += new global::System.EventHandler (this.OnButtonClicked);
		this.button3.Clicked += new global::System.EventHandler (this.OnButtonClicked);
		this.button6.Clicked += new global::System.EventHandler (this.OnButtonClicked);
		this.button9.Clicked += new global::System.EventHandler (this.OnButtonClicked);
	}
}
